name: American Outlaws Las Vegas
favicon: null
layout_spectrum: 0.10362563258968294
typography_spectrum: 0.25786
title: Home of US Soccer Support in Las Vegas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#213b6b'
    - '#7a87a0'
    - '#e62428'
    - '#fba7ae'
  brandStrength: 0.875
  lightness: 0.42034938698634505
  saturation: 0.22610115515999496
  rhythmicContrast: 0.450234288116917
purpose: []
