name: American Outlaws Las Vegas
favicon: null
layout_spectrum: 0.10362563258968294
typography_spectrum: 0.7394996462389827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6692656527739018
  lightness: 0.42034938698634505
  saturation: 0.22610115515999496
  rhythmicContrast: 0.450234288116917
purpose: []
